### ISSUE TITLE
Future chapter for online visitors

### ISSUE THREAD

**Issue by Solcany** [phivk/tolerant-futures#62] opened 2022-05-02 18:57 UTC
We will need an Future option for browser visitors. We can do a prompt e.g. “Thinking of some of the words you’ve played with, please describe how a tolerant future would look like for you?” and then mail to a friend (or I just thought of: submit to a gallery).

**Comment by phivk** [comment] 2022-05-21 14:27
duplicate of https://github.com/phivk/tolerant-futures/issues/101

**Closed by phivk** 2022-05-21 14:27 UTC
Labels: enhancement
